app = 'realtimesearchbox'
primary_region = 'cdg'
console_command = '/rails/bin/rails console'

[build]
  builder = "heroku/buildpacks:20"  # Explicit buildpack

[deploy]
  release_command = './bin/rails db:prepare'
  strategy = "rolling"              # Better deployment strategy

[env]
  PORT = '8080'
  RAILS_ENV = 'production'         # Explicit environment

[processes]
  app = './bin/rails server -b 0.0.0.0 -p ${PORT}'  # Explicit binding

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false       # Prevent automatic shutdown
  auto_start_machines = true
  min_machines_running = 1         # Always keep at least one running
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1