default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  username: postgres
  password: "1234"
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: searchDB

test:
  <<: *default
  database: searchDB_test

production: &production
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  database: realtime_search_box_production
  username: realtime_search_box
  password: <%= ENV["SEARCH_DATABASE_PASSWORD"] %>

queue:
  <<: *production
  database: search_database_queue

cache:
  <<: *default
  database: cache_production
